# Generated by Django 5.1.1 on 2024-11-25 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmd', '0001_squashed_0025_alter_registrocivilmodel_municipality'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailsettingsmodel',
            name='smtp_host',
            field=models.CharField(default=None, null=True, verbose_name='Servidor (SMTP)'),
        ),
        migrations.AddField(
            model_name='emailsettingsmodel',
            name='smtp_password',
            field=models.CharField(default=None, null=True, verbose_name='Contraseña (SMTP)'),
        ),
        migrations.AddField(
            model_name='emailsettingsmodel',
            name='smtp_port',
            field=models.IntegerField(default=None, null=True, verbose_name='Puerto TCP (SMTP)'),
        ),
        migrations.AddField(
            model_name='emailsettingsmodel',
            name='smtp_username',
            field=models.CharField(default=None, null=True, verbose_name='Nombre de Usuario (SMTP)'),
        ),
    ]
