# Generated by Django 5.1.1 on 2024-11-25 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmd', '0026_emailsettingsmodel_smtp_host_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailsettingsmodel',
            name='imap_host',
            field=models.CharField(blank=True, default=None, null=True, verbose_name='Servidor (IMAP)'),
        ),
        migrations.AlterField(
            model_name='emailsettingsmodel',
            name='imap_password',
            field=models.CharField(blank=True, default=None, null=True, verbose_name='Contraseña (IMAP)'),
        ),
        migrations.AlterField(
            model_name='emailsettingsmodel',
            name='imap_port',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Puerto TCP (IMAP)'),
        ),
        migrations.AlterField(
            model_name='emailsettingsmodel',
            name='imap_username',
            field=models.CharField(blank=True, default=None, null=True, verbose_name='Nombre de Usuario (IMAP)'),
        ),
        migrations.AlterField(
            model_name='emailsettingsmodel',
            name='smtp_host',
            field=models.CharField(blank=True, default=None, null=True, verbose_name='Servidor (SMTP)'),
        ),
        migrations.AlterField(
            model_name='emailsettingsmodel',
            name='smtp_password',
            field=models.CharField(blank=True, default=None, null=True, verbose_name='Contraseña (SMTP)'),
        ),
        migrations.AlterField(
            model_name='emailsettingsmodel',
            name='smtp_port',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Puerto TCP (SMTP)'),
        ),
        migrations.AlterField(
            model_name='emailsettingsmodel',
            name='smtp_username',
            field=models.CharField(blank=True, default=None, null=True, verbose_name='Nombre de Usuario (SMTP)'),
        ),
    ]
