# Generated by Django 5.1.1 on 2024-11-26 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmd', '0027_alter_emailsettingsmodel_imap_host_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='correosmodel',
            name='extra_content',
            field=models.TextField(blank=True, null=True, verbose_name='Información Adicional'),
        ),
    ]
