# Generated by Django 5.1.1 on 2024-11-26 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmd', '0028_correosmodel_extra_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('father', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='father_child', to='lmd.person', verbose_name='Padre')),
                ('mother', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mother_child', to='lmd.person', verbose_name='Madre')),
            ],
        ),
    ]
