# Generated by Django 5.1.1 on 2024-11-24 04:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ('security', '0001_initial'), ('security', '0002_identityuser_delete_user'), ('security', '0003_alter_identityuser_dni_alter_identityuser_dni_number_and_more'), ('security', '0004_s3configuration')
    ]

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentityUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.ImageField(help_text='DNI o Carnet de Identidad', upload_to='', verbose_name='DNI')),
                ('dni_number', models.CharField(help_text='Número de Identidad', verbose_name='No. DNI')),
                ('phone', models.CharField(help_text='Número de teléfono', verbose_name='Teléfono')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='identity', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Datos de Identidad',
                'verbose_name_plural': 'Datos de Identidades',
            },
        ),
        migrations.CreateModel(
            name='S3Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_key', models.CharField(max_length=128, verbose_name='Llave de Acceso')),
                ('secret_key', models.CharField(max_length=128, verbose_name='Llave secreta')),
                ('bucket_name', models.CharField(max_length=128, verbose_name='Nombre del Bucket')),
                ('endpoint_url', models.URLField(verbose_name='URL del servicio')),
                ('is_active', models.BooleanField(default=True, verbose_name='Está activo')),
            ],
            options={
                'verbose_name': 'S3 Configuración',
                'verbose_name_plural': 'S3 Configuración',
            },
        ),
    ]
