# Generated by Django 5.1.1 on 2024-11-24 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0006_alter_user_groups_alter_user_user_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=True, help_text='Indica si el usuario puede entrar en este sitio de administración.', verbose_name='es staff'),
        ),
    ]
