# Generated by Django 5.1.1 on 2024-11-24 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0007_alter_user_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
    ]
