# Generated by Django 5.1.1 on 2024-11-25 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0008_alter_user_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identityuser',
            name='dni',
            field=models.ImageField(blank=True, help_text='DNI o Carnet de Identidad', null=True, upload_to='', verbose_name='DNI'),
        ),
        migrations.AlterField(
            model_name='identityuser',
            name='dni_number',
            field=models.CharField(blank=True, help_text='Número de Identidad', null=True, verbose_name='No. DNI'),
        ),
        migrations.AlterField(
            model_name='identityuser',
            name='phone',
            field=models.CharField(blank=True, help_text='Número de teléfono', null=True, verbose_name='Teléfono'),
        ),
    ]
