name: Docker automated deployment

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:


jobs:

  build:
    runs-on: self-hosted
    env:
      IMAGE: ghcr.io/${{ secrets.CR_USER }}/automation:${{ github.run_id }}
      
    steps:
    - uses: actions/checkout@v4
    - uses: docker/login-action@v3.3.0
      with:
        # Server address of Docker registry. If not set then will default to Docker Hub
        registry: ghcr.io # optional
        # Username used to log against the Docker registry
        username: ${{ secrets.CR_USER }} # optional
        # Password or personal access token used to log against the Docker registry
        password: ${{ secrets.CR_PAT }} # optional
        # Log out from the Docker registry at the end of a job
        logout: false # optional, default is true
    - name: Build Image using docker compose
      run: docker compose build
    - name: Push the image to the registry
      run: docker compose push
    - name: Deploy the image
      run: docker compose --project-name=automation up --remove-orphans -d
